### ISSUE TITLE
API url redirects to weird url

### ISSUE THREAD

**Issue by tomasstrejcek** [newPOPE/Nette-RestRoute#17]
router is defined as follows:
```php
$router[] = new RestRoute('Api', 'json');
```

I have defined Api modules with Test presenter

when I visit **BASEURL/api/test?access_token=test**

it redirects me to **BASEURL/api/test?action=read&format=xml&data=&query[action]=read&query[format]=xml&query[data]=&query[query][access_token]=test**

*BASEURL is just placeholder for domain name

exactly same thing happesn with nette 2.2.x and 2.3

**Comment by tomasstrejcek** [comment]
(Test presenter doesnt have any methods currently), Is something missing from the docs?

**Comment by newPOPE** [comment]
Thank you for issue. Can you try dev-master now.

**Comment by tomasstrejcek** [comment]
Its working, thanks a lot :)
