### ISSUE TITLE
How can I make this route work over SSL only?

### ISSUE THREAD

**Issue by dejv88** [newPOPE/Nette-RestRoute#20]
Hello, thanks for this route implementation. :)

I was just wondering if I can force this route to work for https URL only? Adding `IRouter::SECURED` to the definition does not work.

**Comment by newPOPE** [comment]
Hi,

flag `SECURED` cannot work because it is not implemented. You can setup (only) https in your webserver or implement this feature :).

Maybe I'll implement it sometimes.

**Comment by dejv88** [comment]
Ok, no problem. I try to go around it somehow. Thanks for the info!
