### ISSUE TITLE
always_populate_raw_post_data

### ISSUE THREAD

**Issue by martinsifra** [newPOPE/Nette-RestRoute#27]
I recieved an error via Tracy: "Cannot modify header information - headers already sent" etc. There weren't any BOM, so I've turned of Tracy and this appers:

Deprecated: Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. in Unknown on line 0

Warning: Cannot modify header information - headers already sent in Unknown on line 0

I absotutely don´t know if it's my incorrectly set up PHP (5.6.13) or if It can be some general . When I uncomment the line in php.ini (-1 has been there yet) everything works even on my Wedos webhosting (PHP 5.6.5) where  always_populate_raw_post_data = 0.

**Comment by newPOPE** [comment]
So on Wedos you still see that warning? Because I using RestRoute on 5.6.x and everything is okay. 
Btw route already uses `php://input` stream see https://github.com/newPOPE/Nette-RestRoute/blob/master/src/RestRoute.php#L220

**Comment by martinsifra** [comment]
On Wedos goes everything well, just on my localhost I had this problem. So I don't know if it's caused by my wrong setup or something more complex. Yes, I know it's using php://input. However I don't understand these thing so, just want to inform, that there can be this bug. Maybe add some lines to documentation, that there can be this problem with newer PHP versions, because Tracy hide the notice and show directly that warning.

**Comment by newPOPE** [comment]
Hi, so I tried it via docker (PHP 5.6.16) and everything works. Default setting for that directive is 0. But I tested it via PHP devel server and no problem. So it can be some general bug/error.
