### ISSUE TITLE
OPTIONS method is not allowed

### ISSUE THREAD

**Issue by martiman** [newPOPE/Nette-RestRoute#28]
We use RestRoute to create API for communication with mobile app. Mobile app is sending OPTIONS before POST and check if we returns 200 code. RestRoute dont allow this method and throw exception.

**Comment by newPOPE** [comment]
You are right OPTIONS method was not implemented. See version [`2.6.1`](https://github.com/newPOPE/Nette-RestRoute/tree/2.6.1#options) where OPTIONS is implemented.
