### ISSUE TITLE
Argument $query passed to ApiModule\TeamsPresenter::actionRead() must be scalar, array given

### ISSUE THREAD

**Issue by emilcieslar** [newPOPE/Nette-RestRoute#33]
Narazil jsem na problém při pokusu o čtení `$query` v `actionRead` metodě. V presenteru moje metoda vypadá asi takto:

```
/**
  * Search for specific teams by a search query
  */
public function actionRead($query)
{
...
}
```

Nezáleží tak úplně co je v ní, protože se to do ní ani nedostane a hodí to následující chybu:

`Argument $query passed to ApiModule\TeamsPresenter::actionRead() must be scalar, array given`

Při volání této url:

`http://localhost/muj-projekt/api/teams/?q=cokoliv`

Je to chyba v RestRoute nebo někde jinde? Díky moc.

**Comment by newPOPE** [comment]
Skus 

```
public function actionRead($query = []) ...

**Comment by emilcieslar** [comment]
Díky moc Adame, zafungovalo. Byl to problém v Nette, v RestRoute nebo jsem úplně dělal něco špatně? Byl bych moc vděčný za podrobnější vysvětlení (až si najdeš chvíli), abych se příště vyvaroval podobným problémům. Mimochodem velmi bych ocenil dokumentaci k file uploadu, pokud to je možné. Díky moc!

**Comment by newPOPE** [comment]
Myslim, ze to funguje tak ze si schopny si vynutit aku taku typovost pri action, render metode. Ked tam napises napr `actionFoo($bool = false)` tak Nette dany parameter pretypuje na bool pripadne `actionBar($number = 0)` by malo byt typu int aj ked keby si ho vybral z $_GET tak ho vyberies ako string.

**Comment by newPOPE** [comment]
Co sa tyka fileuploadov nieco som doplnil vid. https://github.com/newPOPE/Nette-RestRoute#file-uploads

**Comment by emilcieslar** [comment]
Díky za doplnění dokumentace. Co se týče toho vysvětlení, tak nemyslel jsem úplně jak funguje Nette, které přetypuje daný parametr když ho definuješ tak jak říkáš (i když i toto je pro mě novinkou a díky za vysvětlení). Spíš jsem myslel proč to nefunguje normálně bez toho, aniž bych to přetypoval když v dokumentaci máš vlastně pouze `$query`. Jestli to je chybou RestRoute nebo Nette a pokud je to chybou RestRoute, tak kde v tvém kódu se to konkrétně děje? Projížděl jsem si tvůj source kód a nějak jsem to místo nenašel. Díky moc.

**Comment by newPOPE** [comment]
Ono to nie je moc chyba. Problem bude v tom ze niekto pouziva starsie Nette a tam dana typovost nie je az taka striktna. Posli pls verziu Nette vyskusam pripadne doplnim do doc.

**Comment by emilcieslar** [comment]
~2.3.0 Nemusíš to ale řešit pokud je to úplná blbost, ptal jsem se jenom ze zvědavosti. Díky moc.

**Comment by emilcieslar** [comment]
Mimochodem vyzkoušel jsem ten upload pomocí nové dokumentace a háže to tuto chybu:

```
Service of type Nette\Application\Request used in @var annotation at ApiModule\TeamsPresenter::$request not found. Did you register it in configuration file?
```

A tak jsem ten řádek s injectem smazal a dumpnul si v `actionRead` `$this` a tam ten `request` přímo je, takže nemusíš nic injectovat. Každopádně jsem si zkusil při uploadu souboru dumpnout co mi `$this->request->getFiles()` vrátí a byl to prázdný array. Zkusil jsem tedy ještě přečíst si ty soubory pomocí `$_FILES` a to už mi vrátilo nahrávaný soubor. Takže nevím, kde je tady chyba.

**Comment by newPOPE** [comment]
@emilcieslar tak tu neviem kde by mohol byt problem, resp. ma nic nenapada. Podpora pre Files bola pridana v https://github.com/newPOPE/Nette-RestRoute/pull/31/files. Ja to pre subory ale momentalne nepouzivam.

**Comment by emilcieslar** [comment]
Pokud se mi podaří dostat na úroveň, abych to nějak rozumně opravil, tak pošlu, ale ještě se na to necítím :)
