### ISSUE TITLE
/api/users?foo=bar&page=1 automaticky spadne do actionReadAll

### ISSUE THREAD

**Issue by emilcieslar** [newPOPE/Nette-RestRoute#34]
Podle dokumentace by se `$query` měla definovat v URL takto:

```
/api/users?foo=bar&page=1
```

Pokud to ale takto nadefinuji, tak mi ta `$query` spadne do `actionReadAll` metody. Místo toho to musím nadefinovat takto:

```
/api/users/?foo=bar&page=1
```

(přidat **/**) aby to fungovalo správně. Je to záměr, aby to padalo do `actionReadAll` nebo jsi jenom zapomněl v dokumentaci přidat lomítko? Kdybych neměl nadefinovanou `actionReadAll`, tak bych na to asi nepřišel.

**Comment by newPOPE** [comment]
Trochu nerozumiem co potrebujes resp co je zle?.

Podla https://github.com/newPOPE/Nette-RestRoute#read-all RestRoute proste pusti `actionReadAll` ak nenajde resource ID (https://github.com/newPOPE/Nette-RestRoute#read-with-resource-id) to co je za otaznikom v URL na to nema dopad. Cize GET parametre sa proste sparsuju a poslu do action *** ako pole.

**Comment by emilcieslar** [comment]
Je to jenom detail v dokumentaci, protože tam máš napsáno:

```
/api/users?foo=bar&page=1 → \ApiModule\UsersPresenter::actionRead
```

Ve skutečnosti by to ale mělo být buď:

```
/api/users?foo=bar&page=1 → \ApiModule\UsersPresenter::actionReadAll
```

anebo

```
/api/users/?foo=bar&page=1 → \ApiModule\UsersPresenter::actionRead
```

Nevím jestli je to chyba v nějakém mém nastavení, ale to lomítko hraje celkem zásadní roli v rozhodování jestli pustit actionReadAll nebo actionRead a když ho tam nedáš a chceš číst $query v actionRead, tak tam nebude.

**Comment by newPOPE** [comment]
Aha uz som v obraze. Ty myslis toto https://github.com/newPOPE/Nette-RestRoute#query-params kde je chyba a ma tam byt ...ReadAll... kedze chyba v URL resourceID.

**Comment by newPOPE** [comment]
Fixed 2a4af86

**Comment by emilcieslar** [comment]
Perfektní :) díky za rychlé reakce. Jinak je celé RestRoute skvělá práce, musel si na tom nechat hodně času.

**Comment by newPOPE** [comment]
Thx
